export const BOT_WALLET_ADDRESS = "6BxjVVd8Z9s5YhYSHtuLj4dBWFMeuC3QKq6ZFzeHPCjz";
export const BOT_WALLET_PRIVATE_KEY = "3h5jFCfLbtqa2rbN9ne6XGypA8wgYcJzHKga5FtdsSwYrnPT4rWt8YBMcq7qoAUVdcdiSjLy8qrfTgfHk8eYzjzG";
